### ISSUE TITLE
import paths are not set up correctly for python3

### ISSUE THREAD

**Issue by keithbriggs** [sahands/simple-sat#2]
kbriggs:~/Downloads/simple-sat-master/src> python2 sat.py -v --input tests/simple/02.in 
Trying 1 = 0
Trying 2 = 0
Trying 3 = 0
Current watchlist:
1: 
~1: ~1 ~3
2: 
~2: 1 ~2
3: 1 2 3
~3: 
Current assignment: ~1 ~2 ~3
Clause 1 2 3 contradicted.
Trying 3 = 1
Found satisfying assignment #0:
~1 ~2 3

kbriggs:~/Downloads/simple-sat-master/src> python3 sat.py -v --input tests/simple/02.in 
Traceback (most recent call last):
  File "sat.py", line 18, in <module>
    from solvers import recursive_sat
  File "/home/kbriggs/Downloads/simple-sat-master/src/solvers/recursive_sat.py", line 6, in <module>
    from watchlist import update_watchlist
ImportError: No module named 'watchlist'

**Comment by keithbriggs** [comment]
It should be
from .watchlist import update_watchlist
, then it works in py2 and py3

**Comment by sahands** [comment]
Thanks for reporting this as well. Fixed.
