### ISSUE TITLE
-r option missing 

### ISSUE THREAD

**Issue by FredGannett** [sahands/simple-sat#3]
The -r recursive option is missing from the code.
The readme and text on the from page has 
 -r, --recursive       use the recursive backtracking algorithm.
but the downloaded code does not

$ python sat.py  -i tests/simple/03.in 
A ~B C
$ python sat.py  -r -i tests/simple/03.in 
usage: sat.py [-h] [-v] [-a] [-b] [--starting_with STARTING_WITH]
              [--iterative] [-i INPUT] [-o OUTPUT]
sat.py: error: unrecognized arguments: -r

There is no -r in the code.
$ grep parser.add_argument sat.py 
    parser.add_argument('-v',
    parser.add_argument('-a',
    parser.add_argument('-b',
    parser.add_argument('--starting_with',
    parser.add_argument('--iterative',
    parser.add_argument('-i',
    parser.add_argument('-o',

**Comment by sahands** [comment]
Thanks for pointing this out @FredGannett. f67e4fbd8bfdbb44db541f73aa84e7df71851bdc fixed this.
